# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1507111016);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1507111136);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1507114256);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1507110896);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1507110776);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1507115806);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 2);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migrated-sync-button", true);
user_pref("browser.migration.version", 50);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.seen-tourset-version", 1);
user_pref("browser.onboarding.tour-type", "update");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1507115780851");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1507119380851");
user_pref("browser.search.highlightCount", 2);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20170928135628");
user_pref("browser.slowStartup.averageTime", 5274);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20170928135628");
user_pref("browser.startup.homepage_override.mstone", "56.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":4}");
user_pref("browser.tabs.remote.autostart.2", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\",\"sync-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"pocket-button\",\"screenshots_mozilla_org-browser-action\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"pocket-button\",\"developer-button\",\"screenshots_mozilla_org-browser-action\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":6,\"newElementCount\":0}");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1507196936149");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1507110600931");
user_pref("datareporting.policy.firstRunTime", "1507110536149");
user_pref("datareporting.sessions.current.activeTicks", 86);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 7289);
user_pref("datareporting.sessions.current.main", 1093);
user_pref("datareporting.sessions.current.sessionRestored", 7901);
user_pref("datareporting.sessions.current.startTime", "1507110532971");
user_pref("datareporting.sessions.current.totalTime", 5236);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.ipc.processCount.web", 4);
user_pref("dom.mozApps.used", true);
user_pref("e10s.rollout.cohort", "multiBucket4");
user_pref("e10s.rollout.cohortSample", "0.823528");
user_pref("e10s.rollout.cohortSample.multi", "0.806979");
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 22);
user_pref("extensions.e10s.rollout.blocklist", "");
user_pref("extensions.e10s.rollout.hasAddon", false);
user_pref("extensions.e10s.rollout.policy", "50allmpc");
user_pref("extensions.e10sBlockedByAddons", true);
user_pref("extensions.e10sMultiBlockedByAddons", true);
user_pref("extensions.getAddons.cache.lastUpdate", 1507111017);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "56.0");
user_pref("extensions.lastPlatformVersion", "56.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shield-recipe-client.first_run", false);
user_pref("extensions.shield-recipe-client.startupExperimentMigrated", true);
user_pref("extensions.shield-recipe-client.startupExperimentPrefs.privacy.trackingProtection.enabled", true);
user_pref("extensions.shield-recipe-client.user_id", "1b13ac1f-28b1-4b2f-a7cc-9ce90aefeaa6");
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"screenshots@mozilla.org\":\"c61f11be-9272-4b41-801b-01865c0da7fa\"}");
user_pref("gecko.buildID", "20150125222008");
user_pref("gecko.handlerService.migrated", true);
user_pref("gecko.mstone", "35.0.1");
user_pref("idle.lastDailyNotification", 1507111629);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1507115780);
user_pref("media.gmp-gmpopenh264.version", "1.6");
user_pref("media.gmp-manager.buildID", "20170928135628");
user_pref("media.gmp-manager.lastCheck", 1507115779);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1507111629);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugins.ctprollout.cohort", "user-changed-from-test");
user_pref("plugins.ctprollout.cohortSample", "0.072745");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1507111629);
user_pref("toolkit.startup.last_success", 1507115775);
user_pref("toolkit.telemetry.previousBuildID", "20170928135628");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
